# Generated by Django 4.2.23 on 2025-06-28 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='answer',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='question',
            new_name='front',
        ),
    ]
